### PR TITLE
Integrate github_repo_summary.py script for improved repo documentation

### PR DESCRIPTION
**Pull request by anderote**
## Summary
This pull request integrates the `github_repo_summary.py` script into the WordCells repository. The script generates a markdown file, `github_repo_summary.md`, containing a summary of all the code files in the repository. This will help maintain better documentation of our project structure and make it easier for new contributors to understand the organization of the codebase.

## Motivation
As we all know, WordCells is a game designed for people with bad math skills and spatial reasoning. The game allows these individuals, whom we affectionately call "wordcels," to solve word games and boost their confidence. However, we also understand that wordcels might struggle with navigating complex structures and aligning their expectations in life. By providing a clear and concise summary of our codebase, we aim to make it more accessible for wordcels or any other potential contributors who might not have a strong background in code organization.

## Changes
- Added `github_repo_summary.py` script to the top-level directory of the repository
- The script will exclude itself from the generated summary

Please review the changes and let me know if there's anything else needed before merging this pull request. Thank you!

### CODE REVIEW

**Review by shiraeisenberg — CHANGES_REQUESTED** [review]
remove .idea files or add to gitignore

**Review by anderote — COMMENTED** [review]
removed .idea

**Review by shiraeisenberg — APPROVED** [review]
beautiful and good

**Comment by anderote** [comment]
approved

**Review by anderote — COMMENTED** [review]
well done shoggo

**Pull request merged**
